---
- name: Create users from vars file
  hosts: localhost
  gather_facts: false
  vars_files:
    - users.yml

  tasks:
    - name: Create users
      ansible.builtin.user:
        name: "{{ item['user'] }}"
        groups: "{{ item['group'] }}"
        comment: "{{ item['first'] | upper }} + ' ' + {{ item['last'] | upper }}"
        password: "{{ lookup('ansible.builtin.password', '/tmp/passwords', encrypt=sha512_crypt) }}"
      loop: "{{ users }}"
