---
- name: Create users from vars file
  hosts: all
  gather_facts: false
  vars_files:
    - users.yml

  tasks:
    - name: Create users along with a password file for each user
      ansible.builtin.user:
        name: "{{ item['name'] }}"
        groups: "{{ item['group'] }}"
        comment: "{{ item['first'] | capitalize + ' ' + item['last'] | capitalize }}"
        password: "{{ lookup('ansible.builtin.password', '/tmp/' + item['name'] + '_passwordfile') | password_hash('sha512') }}"
      loop: "{{ users }}"

    - name: Copy password files from running container to hosts
      ansible.builtin.copy:
        src: "{{ '/tmp/' + item['name'] + '_passwordfile' }}"
        dest: "{{ '/tmp/' + item['name'] + '_passwordfile' }}"
      loop: "{{ users }}"
